openapi: 3.0.1
info:
  title: BillingGatewayAPI
  description: API Definition of BillingGatewayAPI
  version: 1.0.0
servers:
  - url: http://localhost:8290/api
  - url: https://localhost:8253/api
paths:
  /legacy/billing/{+path}:
    get:
      parameters:
        - name: +path
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
    put:
      parameters:
        - name: +path
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    post:
      parameters:
        - name: +path
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
    delete:
      parameters:
        - name: +path
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
  /v2/billing/auth/login:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /v2/billing/invoices:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /v2/billing/invoices/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
  /v2/billing/invoices/{id}/pay:
    put:
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
          application/xml:
            schema:
              type: object
              xml:
                name: payload
        required: false
      responses:
        default:
          description: Default response
  /v2/billing/clients/{clientId}/invoices:
    get:
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
  /v2/billing/clients/{clientId}/total:
    get:
      parameters:
        - name: clientId
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        default:
          description: Default response
  /market/indices:
    get:
      responses:
        default:
          description: Default response
  /market/stocks:
    get:
      responses:
        default:
          description: Default response
  /market/stocks/{symbol}:
    get:
      parameters:
        - name: symbol
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: Default response
  /health:
    get:
      responses:
        default:
          description: Default response
